name: Bug Report
description: File a bug report
title: "Bug "
labels: ["bug", "triage"]
assignees:
  - C-EO
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: systems
    attributes:
      label: System Check
      description: Please define your OS.
      options:
        -  Raspberry Pi OS 32 bit
        -  Raspberry Pi OS 64 bit
        -  Raspberry Pi OS full
        -  Twister OS 1.8.5 and onwards
        -  Ubuntu 16.04
        -  Ubuntu 18.04 and onwards
        -  Kali Linux
        -  Bullseye
        -  Android
        -  ChromeOS
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: Paste your terminal or log output here.
      render: bash
  - type: dropdown
    id: reproduction
    attributes:
      label: Bug Reproduction
      description: Did you try to reproduce the bug on your end?
      options:
        - "Yes"
        - "No"
    validations: 
      required: true
  - type: textarea
    id: morelogdetails
    attributes:
      label: Bug Reproduction (More Details)
      description: If you answered yes above, please paste your code block below. This will be automatically formatted into code, so need for backticks.
      placeholder: Paste your code block here.
      render: bash
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/C-EO/nitely/blob/master/docs/code_of_conduct.md) and [Contributing Guidlines](https://github.com/C-EO/nitely/blob/master/docs/contributing.md)
      options:
        - label: I agree to follow this project's **Code of Conduct** and **Contributing Guidlines**.
          required: true
