blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/qedTfxVDRP
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://docs.nitely.vercel.app
    about: You can find our docs here.
