name: greeting

on: 
  pull_request:
    types: opened
  issues:
    types: opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hello there 👋
          Thanks for submitting your first issue to the Nitely App Store project! We'll try to get back to you as soon as possible. 
          In the meantime, we encourage you join our [Discord server](https://discord.gg/qedTfxVDRP), where you can ask any questions you might have.
        pr-message: |
          Hello there 👋
          Thanks for submitting your first pull request to the Nitely App Store project! We'll review your contributions soon. 
          In the meantime, we encourage you to read our [guide to creating an app](https://docs.nitely.vercel.app), and to join our [Discord server](https://discord.gg/qedTfxVDRP), where you can ask us questions you might have. 
